charlink/urls.py
from django.urls import path

from . import views

app_name = 'charlink'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard_post, name='dashboard_post'),
    path('login/', views.login_view, name='login'),
    path('audit/corp/<int:corp_id>/', views.audit, name='audit_corp'),
    path('audit/user/<int:user_id>/', views.audit_user, name='audit_user'),
    path('audit/app/<str:app>/', views.audit_app, name='audit_app'),
    path('search/', views.search, name='search'),
    path('admin/', views.admin_imported_apps, name='admin_imported_apps'),
    path('admin/toggle_visible/<str:app_name>/', views.toggle_app_visible, name='toggle_app_visible'),
    path('admin/toggle_selection/<str:app_name>/', views.toggle_app_default_selection, name='toggle_app_default_selection'),
]

charlink/templates/charlink/admin_imported_apps.html
{% extends 'charlink/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Charlink Imported Apps" %}{% endblock page_title %}

{% block charlink_page_header %}<h1 class="page-header text-center">{% translate "Imported Apps" %}</h1>{% endblock charlink_page_header %}

{% block charlink_content %}
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <button class="nav-link active" id="imported-tab" data-bs-toggle="tab" data-bs-target="#imported" type="button" role="tab" aria-controls="imported" aria-selected="true">
                        {% translate "Imported" %}
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="duplicated-tab" data-bs-toggle="tab" data-bs-target="#duplicatedApps" type="button" role="tab" aria-controls="duplicatedApps" aria-selected="false">
                        {% translate "Duplicated" %}
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="failed-tab" data-bs-toggle="tab" data-bs-target="#failedApps" type="button" role="tab" aria-controls="failedApps" aria-selected="false">
                        {% translate "Failed to import" %}
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="missing-tab" data-bs-toggle="tab" data-bs-target="#missingApps" type="button" role="tab" aria-controls="missingApps" aria-selected="false">
                        {% translate "Missing imports" %}
                    </button>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                <div class="tab-pane fade text-center show active" id="imported" role="tabpanel" aria-labelledby="imported-tab" tabindex="0">
                    <div class="accordion" id="importedAccordion">
                        {% for app, import in imported_apps.items %}
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ app }}" aria-expanded="false" aria-controls="collapse{{ app }}">
                                        {{ app }}
                                    </button>
                                </h2>
                                <div id="collapse{{ app }}" class="accordion-collapse collapse" data-bs-parent="#importedAccordion">
                                    <div class="accordion-body">
                                        <div class="row justify-content-evenly">
                                            {% for login_import in import.imports %}
                                                <div class="col-md-6">
                                                    <div class="card">
                                                        <div class="card-header">{{ login_import.field_label }}</div>
                                                        <div class="card-body">
                                                            {% translate "Visible:" %}
                                                            <a href="{% url "charlink:toggle_app_visible" login_import.get_query_id %}" class="btn {% if login_import.is_ignored %}btn-danger{% else %}btn-success{% endif %} btn-sm ms-2">
                                                                {% if login_import.is_ignored %}
                                                                    <i class="fa-solid fa-eye-slash"></i>
                                                                {% else %}
                                                                    <i class="fa-solid fa-eye"></i>
                                                                {% endif %}
                                                            </a>
                                                        </div>
                                                        <div class="card-body">
                                                            {% translate "Default selection:" %}
                                                            <a href="{% url "charlink:toggle_app_default_selection" login_import.get_query_id %}" class="btn {% if login_import.default_selection %}btn-success{% else %}btn-danger{% endif %} btn-sm ms-2"{% if not login_import.default_selection and not login_import.default_initial_selection %} data-bs-toggle="tooltip" data-bs-placement="top" title="{% translate "WARNING: the developer set this to not selected in order to avoid ESI bans. Ensure you know what you are doing." %}"{% endif %}>
                                                                {% if login_import.default_selection %}
                                                                    <i class="fa-solid fa-check"></i>
                                                                {% else %}
                                                                    <i class="fa-solid fa-times"></i>
                                                                {% endif %}
                                                            </a>
                                                        </div>
                                                        <br>
                                                        <div class="card-body">
                                                            {% translate "Scopes required:" %}
                                                            {{ login_import.scopes|unordered_list|safe }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="tab-pane fade text-center" id="duplicatedApps" role="tabpanel" aria-labelledby="duplicated-tab" tabindex="0">
                    {% if duplicated_apps|length > 0 %}
                        <ul class="list-group">
                            {% for app in duplicated_apps %}
                                <li class="list-group-item">{{ app }}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="card-text">{% translate "No duplicated apps found." %}</p>
                    {% endif %}
                </div>
                <div class="tab-pane fade text-center" id="failedApps" role="tabpanel" aria-labelledby="failed-tab" tabindex="0">
                    {% if failed_to_import|length > 0 %}
                        <ul class="list-group">
                            {% for app, reason in failed_to_import.items %}
                                <li class="list-group-item">{{ app }}: {{ reason }}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="card-text">{% translate "All apps have been imported successfully." %}</p>
                    {% endif %}
                </div>
                <div class="tab-pane fade text-center" id="missingApps" role="tabpanel" aria-labelledby="missing-tab" tabindex="0">
                    {% if no_import|length > 0 %}
                        <ul class="list-group">
                            {% for app in no_import %}
                                <li class="list-group-item">{{ app }}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="card-text">{% translate "No missing imports found." %}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock charlink_content %}

{% block extra_script %}
    $(document).ready(function() {
        $('[data-bs-toggle="tooltip"]').tooltip();
    });
{% endblock extra_script %}

charlink/templates/charlink/app_audit.html
{% extends 'charlink/base.html' %}
{% load charlinkutils %}
{% load charlink_versioned_static %}
{% load i18n %}

{% block page_title %}{% translate "Charlink App Audit" %}{% endblock page_title %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% charlink_static 'charlink/css/added-icons.css' %}">
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}

{% block charlink_page_header %}<h1 class="page-header text-center">{% translate "Links Audit" %}</h1>{% endblock charlink_page_header %}

{% block charlink_content %}
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                {% for login_data in logins.keys %}
                    <li class="nav-item">
                        <button class="nav-link{% if forloop.first %} active{% endif %}" id="{{ login_data.app_label }}-{{ login_data.unique_id }}-tab" data-bs-toggle="tab" data-bs-target="#{{ login_data.app_label }}-{{ login_data.unique_id }}" type="button" role="tab" aria-controls="{{ login_data.app_label }}-{{ login_data.unique_id }}" aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">
                            {{ login_data.field_label }}
                        </button>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                {% for login_data, characters in logins.items %}
                    <div class="tab-pane fade{% if forloop.first %} show active{% endif %}" id="{{ login_data.app_label }}-{{ login_data.unique_id }}" role="tabpanel" aria-labelledby="{{ login_data.app_label }}-{{ login_data.unique_id }}-tab" tabindex="0">
                        <div class="table-reponsive">
                            <table class="table table-aa charlink-table text-center">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th class="text-center">{% translate "Character" %}</th>
                                        <th scope="col" class="text-center">{{ login_data.field_label }}</th>
                                        <th class="text-center">{% translate "Main Character" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for char in characters %}
                                        <tr>
                                            <td><img src="{{ char.portrait_url }}" class="rounded" alt="{{ char }}"></td>
                                            <td>{{ char }}</td>
                                            {% with is_added=char|get_char_attr:login_data.get_query_id %}
                                                {% if is_added %}
                                                    <td><i class="fas fa-check fa-lg"><span class="d-none">A</span></td>
                                                {% else %}
                                                    <td><i class="fas fa-times fa-lg"><span class="d-none">B</span></td>
                                                {% endif %}
                                            {% endwith %}
                                            <td>
                                                <a href="{% url 'charlink:audit_user' char.character_ownership.user_id %}">{{ char.character_ownership.user.profile.main_character }} <i class="fas fa-external-link-alt fa-xs"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock charlink_content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('.charlink-table').DataTable({
            columnDefs: [
                { orderable: false, targets: 0 },
            ],
            order: [],
        });
    });
{% endblock extra_script %}

charlink/templates/charlink/audit.html
{% extends 'charlink/base.html' %}
{% load charlinkutils %}
{% load i18n %}

{% block page_title %}{% translate "Charlink Audit" %}{% endblock page_title %}

{% block charlink_page_header %}<h1 class="page-header text-center">{% translate "Links Audit" %}</h1>{% endblock charlink_page_header %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block charlink_content %}
    <div class="row justify-content-center text-center">
        <div class="col-lg-6">
            <img class="rounded" src="{{ selected.logo_url_64 }}" alt="{{ selected.corporation_name }}">
            <h4 class="my-3">{{ selected.corporation_name }}</h4>
        </div>
        {% if selected.alliance %}
            <div class="col-lg-6">
                <img class="rounded" src="{{ selected.alliance.logo_url_64 }}" alt="{{ selected.alliance.alliance_name }}">
                <h4 class="my-3">{{ selected.alliance.alliance_name }}</h4>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-pills">
                        <li class="nav-item">
                            <button class="nav-link active" id="characters-tab" data-bs-toggle="tab" data-bs-target="#characters-tab-pane" type="button" role="tab" aria-controls="characters-tab-pane" aria-selected="true">
                                {% translate "Characters" %}
                            </button>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="characters-tab-pane"  role="tabpanel" aria-labelledby="characters-tab" tabindex="0">
                            <div class="table-responsive">
                                <table class="table table-aa table-hover" id="tableMembers">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th class="text-center">{% translate "Character" %}</th>
                                            <th class="text-center">{% translate "Main Character" %}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for character in selected|get_corp_members %}
                                            <tr>
                                                <td><img src="{{ character.portrait_url }}" class="rounded" alt="{{ character }}"></td>
                                                <td class="text-center">{{ character }}</td>
                                                <td class="text-center">
                                                    {% if character.character_ownership.user.profile.main_character %}
                                                        <a href="{% url 'charlink:audit_user' character.character_ownership.user_id %}">{{ character.character_ownership.user.profile.main_character }} <i class="fas fa-external-link-alt fa-xs"></i></a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock charlink_content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('#tableMembers').DataTable({
            columnDefs: [
                { orderable: false, targets: 0 },
            ],
            order: [],
        });
    });
{% endblock extra_script %}

charlink/templates/charlink/base.html
{% extends 'allianceauth/base-bs5.html' %}
{% load i18n %}

{% block header_nav_brand %}
    {% translate "CharLink" %}
{% endblock header_nav_brand %}

{% block header_nav_collapse_left %}
    {% if is_auditor %}
        {% include "charlink/menu-left.html" %}
    {% endif %}
{% endblock header_nav_collapse_left %}

{% block header_nav_collapse_right %}
    {% if is_auditor %}
        {% include "charlink/menu-right.html" %}
    {% endif %}
{% endblock header_nav_collapse_right %}

{% block content %}
    <div class="col-lg-12">
        {% block charlink_page_header %}{% endblock charlink_page_header %}
        <div class="container-fluid mt-3 px-0">
            {% block charlink_content %}{% endblock charlink_content %}
        </div>
    </div>
{% endblock content %}

charlink/templates/charlink/charlink.html
{% extends 'charlink/base.html' %}
{% load django_bootstrap5 %}
{% load charlinkutils %}
{% load charlink_versioned_static %}
{% load i18n %}

{% block page_title %}{% translate "CharLink" %}{% endblock page_title %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% charlink_static 'charlink/css/added-icons.css' %}">
{% endblock extra_css %}

{% block charlink_page_header %}<h1 class="page-header text-center">{% translate "Character Linking" %}</h1>{% endblock charlink_page_header %}

{% block charlink_content %}
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <button class="nav-link active" id="login-tab" data-bs-toggle="tab" data-bs-target="#loginForm" type="button" role="tab" aria-controls="loginForm" aria-selected="true">
                        {% translate "Login Form" %}
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="characters-tab" data-bs-toggle="tab" data-bs-target="#linkedCharacters" type="button" role="tab" aria-controls="linkedCharacters" aria-selected="false">
                        {% translate "Linked Characters" %}
                    </button>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                <div class="tab-pane fade text-center container-fluid show active" id="loginForm" role="tabpanel" aria-labelledby="login-tab" tabindex="0">
                    <div class="row justify-content-center">
                        <div class="col-12 my-3">
                            <p>{% translate "Select the apps you want to link from the list. You will be redirected to eveonline website to authenticate and provide the token with all the scopes needed." %}</p>
                        </div>
                        <div class="col-lg-4">
                            <form method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-primary mt-3">{% translate "Login" %}</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade text-center" id="linkedCharacters" role="tabpanel" aria-labelledby="characters-tab" tabindex="0">
                    <div class="table-responsive">
                        <table class="table table-aa align-middle">
                            <thead>
                                <th>{% translate "Character" %}</th>
                                {% for app_imports in characters_added.apps.values %}
                                    {% for login_import in app_imports.imports %}
                                        <th scope="col">{{ login_import.field_label }}</th>
                                    {% endfor %}
                                {% endfor %}
                            </thead>
                            <tbody>
                                {% for char in characters_added.characters %}
                                    <tr>
                                        <td scope="row">{{ char }}</td>
                                        {% for imports in characters_added.apps.values %}
                                            {% for login_data in imports.imports %}
                                                {% with is_added=char|get_char_attr:login_data.get_query_id %}
                                                    {% if is_added %}
                                                        <td><i class="fas fa-check fa-lg"></i></td>
                                                    {% else %}
                                                        <td><i class="fas fa-times fa-lg"></i></td>
                                                    {% endif %}
                                                {% endwith %}
                                            {% endfor %}
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                {% for import_data in characters_added.apps.values %}
                    {% for login_data in import_data.imports %}
                        <li class="nav-item">
                            <button class="nav-link{% if forloop.parentloop.first and forloop.first %} active{% endif %}" id="{{ import_data.app_label }}-{{ login_data.unique_id }}-tab" data-bs-toggle="tab" data-bs-target="#{{ import_data.app_label }}-{{ login_data.unique_id }}" type="button" role="tab" aria-controls="{{ import_data.app_label }}-{{ login_data.unique_id }}" aria-selected="{% if forloop.parentloop.first and forloop.first %}true{% else %}false{% endif %}">
                                {{ login_data.field_label }}
                            </button>
                        </li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                {% for import_data in characters_added.apps.values %}
                    {% for login_data in import_data.imports %}
                        <div class="tab-pane fade {% if forloop.parentloop.first and forloop.first %}show active {% endif %}text-center" id="{{ import_data.app_label }}-{{ login_data.unique_id }}" role="tabpanel" aria-labelledby="{{ import_data.app_label }}-{{ login_data.unique_id }}-tab" tabindex="0">
                            {% translate "Scopes required:" %}
                            {{ login_data.scopes|unordered_list|safe }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock charlink_content %}

charlink/templates/charlink/dashboard_login.html
{% load django_bootstrap5 %}
{% load i18n %}

<div id="charlink-dashboard-widget" class="col-12 mb-3">
    <div class="card px-2">
        <div class="card-body text-center">
            {% include "framework/dashboard/widget-title.html" with title="CharLink" %}
            <div class="row justify-content-center">
                <div class="col-lg-4">
                    <form method="post" action="{% url "charlink:dashboard_post" %}">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit" class="btn btn-outline-info mt-2">{% translate "Login" %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

charlink/templates/charlink/menu-left.html
{% load i18n %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        {% translate "Corporations" %}
    </a>
    <ul class="dropdown-menu">
        {% for corp in available %}
            <li>
                <a class="dropdown-item" href="{% url 'charlink:audit_corp' corp.corporation_id %}">{{ corp.corporation_name }}</a>
            </li>
        {% endfor %}
    </ul>
</li>

<li class="nav-item dropdown ms-3">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        {% translate "Apps" %}
    </a>
    <ul class="dropdown-menu">
        {% for app, import_data in available_apps.items %}
            <li>
                <a class="dropdown-item" href="{% url 'charlink:audit_app' app %}">{{ import_data.imports.0.field_label }}</a>
            </li>
        {% endfor %}
    </ul>
</li>

{% if user.is_superuser %}
    <li class="nav-item ms-3">
        <a class="nav-link" href="{% url "charlink:admin_imported_apps" %}">{% translate "CharLink Admin" %}</a>
    </li>
{% endif %}

charlink/templates/charlink/menu-right.html
{% load i18n %}

<form class="d-flex" role="search" action="{% url 'charlink:search' %}" method="GET">
    <input class="form-control me-2" type="search" name="search_string" placeholder="{% if search_string %}{{ search_string }}{% else %}Search character...{% endif %}" aria-label="{% if search_string %}{{ search_string }}{% else %}Search character...{% endif %}">
    <button class="btn btn-outline-success" type="submit">{% translate "Search" %}</button>
</form>

charlink/templates/charlink/search.html
{% extends 'charlink/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Charlink Search" %}{% endblock page_title %}

{% block charlink_page_header %}<h1 class="page-header text-center">{% translate "Links Audit" %}</h1>{% endblock charlink_page_header %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block charlink_content %}
    <div class="card">
        <div class="card-header text-center">
            <h3 class="card-title">{% translate "Search results" %}</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-aa table-hover" id="tableCharacters">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">{% translate "Character" %}</th>
                            <th class="text-center">{% translate "Corporation" %}</th>
                            <th class="text-center">{% translate "Main Character" %}</th>
                            <th class="text-center">{% translate "Main Corporation" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for character in characters %}
                            <tr>
                                <td><img src="{{ character.portrait_url }}" class="rounded" alt="{{ character }}"></td>
                                <td class="text-center">{{ character }}</td>
                                <td class="text-center">{{ character.corporation_name }}</td>
                                <td class="text-center">
                                    {% if character.character_ownership.user.profile.main_character %}
                                        <a href="{% url 'charlink:audit_user' character.character_ownership.user_id %}">{{ character.character_ownership.user.profile.main_character }} <i class="fas fa-external-link-alt fa-xs"></i></a>
                                    {% endif %}
                                </td>
                                <td class="text-center">{{ character.character_ownership.user.profile.main_character.corporation_name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock charlink_content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('#tableCharacters').DataTable({
            columnDefs: [
                { orderable: false, targets: 0 },
            ],
            order: [],
            searching: false
        });
    });
{% endblock extra_script %}